name:                maypop
version:             0.1.0.0
github:              "githubuser/maypop"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/maypop#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2.2 && < 3
- containers >= 0.6.2.1 && < 0.7
- parsec >= 3.1.14.0 && < 3.2
- logict >= 0.7.1.0 && < 0.8
- indents >= 0.5.0.1 && < 0.6
- constraints >= 0.12 && < 0.13

library:
  source-dirs: src

executables:
  maypop-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maypop

tests:
  maypop-test:
    main:                Spec.lhs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maypop
    - QuickCheck >= 2.14.2 && < 3
    - HUnit >= 1.6.0.0 && < 2
