name: Publish Hugo Site
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Maypop source
              uses: actions/checkout@v2

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.80.0'

            - name: Setup Pandoc
              uses: r-lib/actions/setup-pandoc@v1
              with:
                  pandoc-version: '2.9.2.1'

            - name: Copy Files
              run: ./script/pages.sh

            - name: Build
              run: hugo

            - name: Upload 
              uses: wlixcc/SFTP-Deploy-Action@v1.0
              with:
                  username: 'fedorind'
                  server: flip.engr.oregonstate.edu
                  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
                  local_path: './public'
                  remote_path: '/nfs/stak/users/fedorind/public_html/CS583'
